spring:
  security:
    oauth2:
      client:
        registration:
          su:
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
  profiles:
    include: local
  mvc:
    problemdetails:
      enabled: true
